СОЗДАНИЕ МАССИВОВ

In [32]:
import numpy as np

# Создание массива из обычного списка Python
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)
print("Массив из списка:", array_from_list)

# Создание двумерного массива из вложенных списков
matrix_data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = np.array(matrix_data)
print("Двумерный массив:")
print(matrix)

# Создание массива из нулей
zeros_array = np.zeros(5)
print("Массив из нулей:", zeros_array)

# Создание массива из единиц
ones_array = np.ones((2, 3))  # 2 строки, 3 столбца
print("Массив 2x3 из единиц:")
print(ones_array)

# Создание массива с последовательностью чисел
range_array = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print("Массив с arange:", range_array)


Массив из списка: [1 2 3 4 5]
Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Массив из нулей: [0. 0. 0. 0. 0.]
Массив 2x3 из единиц:
[[1. 1. 1.]
 [1. 1. 1.]]
Массив с arange: [0 2 4 6 8]


АТРИБУТЫ МАССИВОВ

In [33]:


print("Форма матрицы:", matrix.shape)    # Размерность массива
print("Тип данных матрицы:", matrix.dtype) # Тип элементов
print("Количество измерений:", matrix.ndim) # Число осей
print("Общее количество элементов:", matrix.size) # Всего элементов



Форма матрицы: (3, 3)
Тип данных матрицы: int64
Количество измерений: 2
Общее количество элементов: 9


ИНДЕКСИРОВАНИЕ

In [34]:
# Получение отдельного элемента (индексация начинается с 0)
print("Элемент [1,2]:", matrix[1, 2])  # Вторая строка, третий столбец

# Срезы - получение подмассива
print("Первые две строки:")
print(matrix[:2])  # Все столбцы, первые две строки

print("Последний столбец:")
print(matrix[:, -1])  # Все строки, последний столбец

print("Подмассив 2x2 из центра:")
print(matrix[1:3, 0:2])  # Строки 1-2, столбцы 0-1

Элемент [1,2]: 6
Первые две строки:
[[1 2 3]
 [4 5 6]]
Последний столбец:
[3 6 9]
Подмассив 2x2 из центра:
[[4 5]
 [7 8]]


ВЕКТОРНЫЕ ОПЕРАЦИИ

In [35]:
# Создадим два массива для операций
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Поэлементное сложение
sum_arrays = a + b
print("Сложение a + b:", sum_arrays)

# Поэлементное умножение
mult_arrays = a * b
print("Умножение a * b:", mult_arrays)

# Математические функции применяются к каждому элементу
squared = np.square(a)
print("Квадраты элементов a:", squared)

Сложение a + b: [ 6  8 10 12]
Умножение a * b: [ 5 12 21 32]
Квадраты элементов a: [ 1  4  9 16]


СТАТИСТИЧЕСКИЕ ФУНКЦИИ

In [36]:
data = np.array([2, 4, 6, 8, 10, 12])

print("Исходный массив:", data)
print("Среднее значение:", np.mean(data))
print("Стандартное отклонение:", np.std(data))
print("Максимальное значение:", np.max(data))
print("Минимальное значение:", np.min(data))
print("Сумма всех элементов:", np.sum(data))

# Статистика по осям для матрицы
print("Исходная матрица:")
print(matrix)
print("Среднее по столбцам:", np.mean(matrix, axis=0))  # По вертикали
print("Среднее по строкам:", np.mean(matrix, axis=1))   # По горизонтали

Исходный массив: [ 2  4  6  8 10 12]
Среднее значение: 7.0
Стандартное отклонение: 3.415650255319866
Максимальное значение: 12
Минимальное значение: 2
Сумма всех элементов: 42
Исходная матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Среднее по столбцам: [4. 5. 6.]
Среднее по строкам: [2. 5. 8.]
